---
AWSTemplateFormatVersion: "2010-09-09"

Description: "Cognito User Pool"

Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: demo-101
      UsernameAttributes:
        - email

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: demo-101-app
      GenerateSecret: false
      UserPoolId: !Ref CognitoUserPool

  CognitoIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: demo101AppReact
      AllowUnauthenticatedIdentities: false

  AuthenticatedRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Cognito_demo101Auth_Role
      Description: Cognito service auth role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Federated:
                - cognito-identity.amazonaws.com
            Action:
              - sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                cognito-identity.amazonaws.com:aud: !Ref CognitoIdentityPool
              ForAnyValue:StringLike:
                cognito-identity.amazonaws.com:amr: authenticated

  UnAuthenticatedRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Cognito_demo101UnAuth_Role
      Description: Cognito service unauth role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Federated:
                - cognito-identity.amazonaws.com
            Action:
              - sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                cognito-identity.amazonaws.com:aud: !Ref CognitoIdentityPool
              ForAnyValue:StringLike:
                cognito-identity.amazonaws.com:amr: unauthenticated

  CognitoAuthRole:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: oneClick_Cognito_demo101Auth_Role
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - cognito-identity:*
              - mobileanalytics:PutEvents
              - cognito-sync:*
            Resource: "*"
      Roles:
        - !Ref AuthenticatedRole

  CognitoUnAuthRole:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: oneClick_Cognito_demo101UnAuth_Role
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - mobileanalytics:PutEvents
              - cognito-sync:*
            Resource: "*"
      Roles:
        - !Ref UnAuthenticatedRole

  CognitoIdentityPoolSetRoles:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId: !Ref CognitoIdentityPool
      Roles:
        "authenticated": !GetAtt AuthenticatedRole.Arn
        "unauthenticated": !GetAtt UnAuthenticatedRole.Arn

Outputs:
  CognitoUserPoolId:
    Description: "UserPoolId of User Pool"
    Value:
      Ref: "CognitoUserPool"
    Export:
      Name: !Sub "${AWS::Region}-${AWS::StackName}-UserPool"

  CognitoUserPoolClientId:
    Description: "UserPoolAppId of User Pool"
    Value:
      Ref: CognitoUserPoolClient
    Export:
      Name: !Sub "${AWS::Region}-${AWS::StackName}-UserPoolApp"

  CognitoIdentityPoolId:
    Description: "IdentityPoolId of Identity Pool"
    Value:
      Ref: CognitoIdentityPool
    Export:
      Name: !Sub "${AWS::Region}-${AWS::StackName}-CognitoIdentityPoolId"
